debug: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: CNCITY_APP
